---
- hosts: all
  become: yes
  tasks:
    - name: Run shell
      shell: uptime
      register: out

    - debug: var=out.stdout_lines

    - name: run shell
      shell: hostname
      register: host

    - debug: var=host.stdout_lines
